# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: objectstore.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'objectstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11objectstore.proto\x12\x0bobjectstore\x1a\x1bgoogle/protobuf/empty.proto\"M\n\x07WriteOp\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.objectstore.WriteOpType\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\rUpdateRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\",\n\tListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nsize_bytes\x18\x02 \x01(\x04\"7\n\x0cListResponse\x12\'\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x16.objectstore.ListEntry\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\"x\n\rStatsResponse\x12\x14\n\x0clive_objects\x18\x01 \x01(\x04\x12\x13\n\x0btotal_bytes\x18\x02 \x01(\x04\x12\x0c\n\x04puts\x18\x03 \x01(\x04\x12\x0c\n\x04gets\x18\x04 \x01(\x04\x12\x0f\n\x07\x64\x65letes\x18\x05 \x01(\x04\x12\x0f\n\x07updates\x18\x06 \x01(\x04*9\n\x0bWriteOpType\x12\x07\n\x03PUT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\t\n\x05RESET\x10\x03\x32\xe8\x03\n\x0bObjectStore\x12\x36\n\x03Put\x12\x17.objectstore.PutRequest\x1a\x16.google.protobuf.Empty\x12\x38\n\x03Get\x12\x17.objectstore.GetRequest\x1a\x18.objectstore.GetResponse\x12<\n\x06\x44\x65lete\x12\x1a.objectstore.DeleteRequest\x1a\x16.google.protobuf.Empty\x12<\n\x06Update\x12\x1a.objectstore.UpdateRequest\x1a\x16.google.protobuf.Empty\x12\x39\n\x04List\x12\x16.google.protobuf.Empty\x1a\x19.objectstore.ListResponse\x12\x37\n\x05Reset\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12;\n\x05Stats\x12\x16.google.protobuf.Empty\x1a\x1a.objectstore.StatsResponse\x12:\n\nApplyWrite\x12\x14.objectstore.WriteOp\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'objectstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEOPTYPE']._serialized_start=541
  _globals['_WRITEOPTYPE']._serialized_end=598
  _globals['_WRITEOP']._serialized_start=63
  _globals['_WRITEOP']._serialized_end=140
  _globals['_PUTREQUEST']._serialized_start=142
  _globals['_PUTREQUEST']._serialized_end=182
  _globals['_GETREQUEST']._serialized_start=184
  _globals['_GETREQUEST']._serialized_end=209
  _globals['_DELETEREQUEST']._serialized_start=211
  _globals['_DELETEREQUEST']._serialized_end=239
  _globals['_UPDATEREQUEST']._serialized_start=241
  _globals['_UPDATEREQUEST']._serialized_end=284
  _globals['_LISTENTRY']._serialized_start=286
  _globals['_LISTENTRY']._serialized_end=330
  _globals['_LISTRESPONSE']._serialized_start=332
  _globals['_LISTRESPONSE']._serialized_end=387
  _globals['_GETRESPONSE']._serialized_start=389
  _globals['_GETRESPONSE']._serialized_end=417
  _globals['_STATSRESPONSE']._serialized_start=419
  _globals['_STATSRESPONSE']._serialized_end=539
  _globals['_OBJECTSTORE']._serialized_start=601
  _globals['_OBJECTSTORE']._serialized_end=1089
# @@protoc_insertion_point(module_scope)
